// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:69d58a04-28b0-4bbe-949e-adadb8150115",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_NQP8RYOak",
    "aws_user_pools_web_client_id": "10unhiso9gc7fi9f80l1ckr63h",
    "aws_appsync_graphqlEndpoint": "https://cqjm5zlg4nge5d4ajno5ccsdhq.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-csojgajmfvf2lm42tjfgtptmo4"
};


export default awsmobile;
