// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:03510299-fb40-4e52-9ad7-025e3f5d1221",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_OPGgxA6uG",
    "aws_user_pools_web_client_id": "5khatfudt40muvbaa3nipdc8ud",
    "aws_appsync_graphqlEndpoint": "https://2xi2fekkjrd35e3rkwwtr4lkbu.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
